config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'signup', to: 'users#new' #urlが'signupになる'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :blogs, only: %i[create,destroy]
  resources :users, only: %i[index show new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "user_id"

  STATUS_VALUES= %w(draft user_only public)
  validates :title, presence :ture, lenghth: {maximum: 200}
  validates :content, :posted_at, presence: true
  validates :status, inclusion: { in: STATUS_VALUES }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :blogs, dependent: :destroy
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+[a-z]+\z/i },
                    uniqueness: {case_sensitive: false } #uniquenessは重複を許さないバリデーション case_sensitive = 大文字小文字を区別しない
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = 'ログインに成功しました'
      redirect_to @user
    else
      flash.now[:denger] = "ログインに失敗しました"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end

  private

  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true #ログイン成功
    else
      return false #ログイン失敗
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザー登録が完了しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました'
      render :new
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.save
      flash[:success] = 'ユーザー情報をアップデートしました'
      redirect_to @user
    else
      flash[:danger] = 'ユーザー情報のアップデートに失敗しました'
      render "edit"
    end
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any?%>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message|%>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <header>
        <%= render 'shared/navbar' %>
      </header>
      <main>
        <%= yield %>
        <%= javascript_pack_tag 'hello_vue' %>
      </main>
      <footer>
        <%= render 'shared/footer' %>
      </footer>
    </div>

  </body>
</html>

app/views/shared/_footer.html.erb
<div class="text-center">
  <%='このサイトについて'%> |
  Copyright (c) Hirokin.
</div>

app/views/shared/_login_form.html.erb
<div class="text-center">
  <h1>ログイン</h1>

  <%= form_for(:session, url: login_path) do |f| %>
    <div class="form-group">
      <%= f.label :email, 'メールアドレス'%>
      <%= f.email_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :password, 'パスワード'%>
      <%= f.password_field :password, class: 'form-control' %>
    </div>

    <%= f.submit 'ログイン', class: 'btn btn-outline-dark' %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a><%= link_to "My Blog",root_path,class: "navbar-brand"%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Blogs","#",class: "nav-link" %>
      </li>
      <li><%= link_to 'Logout', logout_path, method: :delete,  class: 'nav-link' %></li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Other
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a><%= link_to 'ログアウト',logout_path, class: 'dropdown-item' %></a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
  <h1>過去のブログ</h1>
  <% 5.times do |i| %>
   <li><%= link_to "ブログの見出し", "#" %></li>
  <% end %>

app/views/toppages/index.html.erb
<div class="">
  <div class="text-center">
    <%= javascript_pack_tag 'hello_vue' %>
    <h1>My Blog</h1>
    <li><%= link_to 'Sign_up',signup_path %></li>
    <li><%= link_to 'ログイン',login_path %></li>
  </div>
</div>

app/views/users/_form.html.erb
<div class="text-center">
  <h1>新規ユーザー登録</h1>
</div>
    <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%=f.label :name, '名前' %>
        <%=f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%=f.label :email, 'メールアドレス' %>
        <%=f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%=f.label :password, 'パスワード' %>
        <%=f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%=f.label :password_confirmation, 'パスワード(再入力)' %>
        <%=f.password_field :password_confirmation, class: 'form-control' %>
      </div>

    <%= f.submit '登録', class: 'btn btn-outline-dark'%>
   <% end %>

app/views/users/_users.html.erb
<%if users.any? %>
  <ul class="">
    <% user.each do |user|%>
      <div>
        <%= user.name %>
      </div>
      <div>
        <p><%=link_to 'プロフィール',user_path(user)%></p>
      </div>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<%= render 'form', users: @users %>

app/views/users/show.html.erb
<%=@user.name %>